name: Contributor Helper

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-cool/contributor-helper@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-files: 'DEMO.base.md'
          update-places: '## Contributors List/## hi'
          repo: 'antvis/X6'
          style: 'base'
          avatar-width: '66'

      - uses: actions-cool/contributor-helper@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-files: 'DEMO.simple.md'
          update-places: '## Contributors List/## hello'
          repo: 'antvis/X6'
          style: 'simple'
          avatar-width: '66'

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git pull
          git add -A
          git commit -m "ðŸ¤– Auto update contributors" || exit 0
          git push
